# Testování hypotéz {#sec-testovani}

Testování statistikcké hypotézy je proces 
Zavádíme pojmy nulové $\mathrm{H}_0$ a alternativní hypotézy $\mathrm{H}_a$. 
Pod *testováním hypotéz* potom rozumíme proces, který na základě 
vlastností datové sady pocházející z náhodného výběru rozhodne o zamítnutí, 
či nezamítnutí nulové hypotézy.

Nulová hypotéza má ve většině případů neutrání až poněkud negativní znění. 
Například "neexistuje rozdíl mezi středními hodnotami", "testované rozdělení 
není odlišné od normálního" apod. Její konstrukce víceméně odráží opak toho, 
co se na sesbíraných datech snažíme vysledovat.

## Postup testování statistické hypotézy:

1.  Formulace nulové $\mathrm{H}_0$ a alternativní $\mathrm{H}_a$ hypotézy.\
2.  Volba hladiny významnosti $\alpha$.\
3.  Volba testovací statistiky.\
4.  Určení kritického oboru testové statistiky.
5.  Vyhodnocení testu s pomocí p-hodnoty.

Výsledkem testování je buď a) zamítnutní nulové hypotézy[^07_testovani-1] b) nezamítnutní nulové hypotézy.

[^07_testovani-1]: Zamítnutí nulové hypotézy **neznamená, že nulová hypotéza neplatí**, ale znamená to, že data nevykazují objektivní důvody k jejímu přijetí.

```{=html}
<hr>
<table>
  <tr>
    <td rowspan="2"><b>Rozhodnutí</b></td><td colspan="2"><b>Skutečnost</b></td>
  </tr>
  <tr>
    <td>$$\mathrm{H}_0$$</td><td>$$\neg \mathrm{H}_0$$</td>
  </tr>
  <tr>
    <td>Nazamítáme $$\mathrm{H}_0$$</td><td>Správné rozhodnutí: $$P = 1 - \alpha$$</td><td>Nastává chyba II. druhu: $$P = \beta$$</td>
  </tr>
  <tr>
    <td>Zamítáme $$\mathrm{H}_0$$</td><td>Chyba I. druhu: $$P = \alpha$$</td><td>Správné rozhodnutí: $$P = 1- \beta$$</td>
  </tr>
</table>
```


## p-hodnota

Místo porovnání hodnoty testovacího kritéria s kritickými hodnotami lze pro rozhodování o platnosti či neplatnosti nulové hypotézy použít i tzv. *p-hodnotu* (anglicky p-value). Definice p-hodnoty je poněkud obšírná - *jedná se o odhad pravděpodobnosti, že daný výsledek nebo výsledek, který je ještě extrémnější než ten pozorovaný, mohl nastat náhodou, za předpokladu, že nulová hypotéza je pravdivá*.

## $100(1-\alpha)\%$ interval spolehlivosti

$$
\bar{x} - 1.96\dfrac{\sigma}{\sqrt{n}}\leq\mu\leq \bar{x} + 1.96\dfrac{\sigma}{\sqrt{n}}
$$

$$
\bar{x} - t_{1-\alpha/2(\nu)}\dfrac{\sigma}{\sqrt{n}}\leq\mu\leq \bar{x} + t_{1-\alpha/2(\nu)}\dfrac{\sigma}{\sqrt{n}}
$$

kde $\nu=n-1$ je počet stupňů volnosti.

-

Pravděpodobnost platnosti hypotézy
