project:
  type: book
  output-dir: docs

website:
  title: "Metody vyhodnocování vodohospodářských dat"
  navbar: 
    left:
      - href: index.qmd
      - text: Home
      - intro.qmd
  

book:
  title: "Metody vyhodnocování vodohospodářských dat"
  subtitle: "MVVD ZS 23/24"
  author: "Petr Pavlík"
  favicon: cover.png
  repo-actions: [edit]
  date: today
  chapters:
    - index.qmd
    - intro.qmd
    # - 01_uvod_do_R_1.qmd
    # - 02_uvod_do_R_2.qmd
    # - 03_summary.qmd
    # - 04_popisna.qmd
    # - 05_rozdeleni.qmd
    - 06_odhad.qmd
    #- 07_testovani.qmd
    # - 08_test_1.qmd
    - 09_casove_rady.qmd
    # - 10_hydro_index.qmd
    # - 11_korelace_regrese.qmd
    # - 12_test_2.qmd
    # - references.qmd
    
  
  downloads: [pdf, epub]
  sidebar:
    title: "Metody vyhodnocování VH dat"
    pinned: true
    tools:
      - icon: save
        menu:
          - text: "data.csv"
            url:  "#"
          - text: ""
            url:  "#"
          - text: ""
            url:  "#"

  search: 
    location: sidebar
    type: textbox
  
bibliography: references.bib

format:
  html:
    page-layout: article
    include-after-body: custom.html
    theme: 
      - cosmo
      - style.scss
    max-width: 1600px
    #css: style.css
    code-fold: show
    linkcolor: "#006666"
    highlight-style: syntax.theme

  pdf:
    documentclass: scrreprt

editor: visual
lang: cs-CZ


