::: download_btn
```{css}
#| echo: false

.btn-default,
.btn-default:hover,
.btn-default:active {
  font-size: 20px;
  color: navy;
  background-color: transparent;
  border-color: transparent;
}

.btn-default:hover {
  color: black;
  transition: 0.2s;
}

```

```{r}
#| echo: false
library(downloadthis)
readRDS("data/data.rds") |> 
  download_this(
    output_name = "Sample MOPEX data set",
    output_extension = ".rds",
    button_label = "data.rds",
    button_type = "default",
    has_icon = TRUE,
    icon = "fa fa-save"
  )
```
:::

# Úvod

Tento text je webový průvodce pro cvičení kurzu **ZVZ117E Metody vyhodnocování vodohospodářských dat**. Jeho obsahuje materiály ke všem jednotlivým cvičením spolu se zkrácenou teoretickou částí. Text nemá za ambici vyložit látku komplexně, nenahrazuje přednášky kurzu ani skripta. Jedná se o **průvodce cvičeními**. Vzhledem k tomu, že je tento text orientován na osvojení základních postupů při statistickém zpracování dat, jednotlivé postupy jsou voleny jako nejjednodušší možné. Obecně tedy platí, že veškeré úkony jsou prováděny s didaktickým cílem, který je vytyčen na začátku každého cvičení. Tentýž kód je často možné zapsat elegantněji, nebo efektivněji s pomocí pokročilejších nástrojů, na které je čtenář občas doplňkově upozorněn.

## Doporučená literatura

See @knuth84 for additional discussion of literate programming.
